package wsg.tools.common.io.ffmpeg;

import com.fasterxml.jackson.annotation.JsonAlias;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.time.Duration;
import java.time.LocalDateTime;
import wsg.tools.common.jackson.JsonDurationFormat;

/**
 * The information about the container format of the input multimedia stream.
 *
 * @author Kingen
 * @since 2021/6/4
 */
public class Format {

    @JsonProperty(value = "filename", required = true)
    private String filename;

    @JsonProperty(value = "format_name", required = true)
    private String formatName;

    @JsonProperty(value = "format_long_name", required = true)
    private String formatLongName;

    @JsonProperty(value = "size", required = true)
    private long size;

    @JsonProperty(value = "bit_rate", required = true)
    private long bitRate;

    @JsonProperty(value = "duration", required = true)
    @JsonDurationFormat(format = JsonDurationFormat.Format.DOUBLE)
    private Duration duration;

    @JsonProperty(value = "start_time", required = true)
    private double startTime;

    @JsonProperty(value = "probe_score", required = true)
    private int probeScore;

    @JsonProperty(value = "nb_programs", required = true)
    private int nbPrograms;

    @JsonProperty(value = "nb_streams", required = true)
    private int nbStreams;

    @JsonProperty("tags")
    private FormatTags tags;

    Format() {
    }

    public String getFilename() {
        return filename;
    }

    public String getFormatName() {
        return formatName;
    }

    public String getFormatLongName() {
        return formatLongName;
    }

    public long getSize() {
        return size;
    }

    public long getBitRate() {
        return bitRate;
    }

    public Duration getDuration() {
        return duration;
    }

    public double getStartTime() {
        return startTime;
    }

    public int getProbeScore() {
        return probeScore;
    }

    public int getNbPrograms() {
        return nbPrograms;
    }

    public int getNbStreams() {
        return nbStreams;
    }

    public FormatTags getTags() {
        return tags;
    }

    public static class FormatTags {

        @JsonProperty("title")
        private String title;

        @JsonProperty("encoder")
        @JsonAlias("ENCODER")
        private String encoder;

        @JsonProperty("creation_time")
        @JsonFormat(pattern = "yyyy-MM-dd'T'HH:mm:ss.SSSSSS'Z'", timezone = "utc")
        private LocalDateTime creationTime;

        @JsonProperty("Creation Date")
        @JsonFormat(pattern = "M/d/yyyy H:mm:ss")
        private LocalDateTime creationDate;

        @JsonProperty("author")
        private String author;

        @JsonProperty("Generated By")
        private String generatedBy;

        @JsonProperty("Encoded/Released by")
        private String releasedBy;

        @JsonProperty("major_brand")
        private String majorBrand;

        @JsonProperty("minor_version")
        private Integer minorVersion;

        @JsonProperty("compatible_brands")
        private String compatibleBrands;

        @JsonProperty("copyright")
        private String copyright;

        @JsonProperty("comment")
        private String comment;

        @JsonProperty("ASMRuleBook")
        private String asmRuleBook;

        @JsonProperty("Audiences")
        private String audiences;

        @JsonProperty("audioMode")
        private String audioMode;

        @JsonProperty("Description")
        @JsonAlias("description")
        private String description;

        @JsonProperty("Email")
        private String email;

        @JsonProperty("HomeWeb")
        private String website;

        @JsonProperty("Keywords")
        private String keywords;

        @JsonProperty("Modification Date")
        @JsonFormat(pattern = "M/d/yyyy H:mm:ss")
        private LocalDateTime modificationDate;

        @JsonProperty("videoMode")
        private String videoMode;

        @JsonProperty("software")
        private String software;

        @JsonProperty("File ID")
        private String fileId;

        FormatTags() {
        }

        public String getTitle() {
            return title;
        }

        public String getEncoder() {
            return encoder;
        }

        public LocalDateTime getCreationTime() {
            return creationTime;
        }

        public LocalDateTime getCreationDate() {
            return creationDate;
        }

        public String getAuthor() {
            return author;
        }

        public String getGeneratedBy() {
            return generatedBy;
        }

        public String getReleasedBy() {
            return releasedBy;
        }

        public String getMajorBrand() {
            return majorBrand;
        }

        public Integer getMinorVersion() {
            return minorVersion;
        }

        public String getCompatibleBrands() {
            return compatibleBrands;
        }

        public String getCopyright() {
            return copyright;
        }

        public String getComment() {
            return comment;
        }

        public String getAsmRuleBook() {
            return asmRuleBook;
        }

        public String getAudiences() {
            return audiences;
        }

        public String getAudioMode() {
            return audioMode;
        }

        public String getDescription() {
            return description;
        }

        public String getEmail() {
            return email;
        }

        public String getWebsite() {
            return website;
        }

        public String getKeywords() {
            return keywords;
        }

        public LocalDateTime getModificationDate() {
            return modificationDate;
        }

        public String getVideoMode() {
            return videoMode;
        }

        public String getSoftware() {
            return software;
        }

        public String getFileId() {
            return fileId;
        }
    }
}