spring:
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
  datasource:
    url: jdbc:mysql://192.168.1.108:3306/tools?useUnicdeo=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: root
    data: classpath:sql/init.sql
  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate.format_sql: true
    hibernate:
      ddl-auto: update
  resources:
    static-locations: classpath:/
server:
  address: 0.0.0.0
  port: 6808
logging:
  level:
    org.hibernate.type.descriptor.sql.BasicBinder: trace