spring:
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://192.168.1.108:3306/tools?useUnicdeo=true&characterEncoding=UTF-8
    username: root
    password: root
  jpa:
    show-sql: true
server:
  address: 0.0.0.0
  port: 6808